// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplategateway = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/client/count": {
            "post": {
                "description": "查询客户端数量",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "查询客户端数量",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/client/create": {
            "post": {
                "description": "创建客户端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "创建客户端",
                "parameters": [
                    {
                        "description": "客户端信息",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Client"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Client"
                        }
                    }
                }
            }
        },
        "/client/export": {
            "get": {
                "description": "导出客户端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "product"
                ],
                "summary": "导出客户端",
                "responses": {}
            }
        },
        "/client/import": {
            "post": {
                "description": "导入客户端",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "导入客户端",
                "parameters": [
                    {
                        "type": "file",
                        "description": "压缩包",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/client/list": {
            "get": {
                "description": "查询客户端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "查询客户端",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Client"
                        }
                    }
                }
            }
        },
        "/client/search": {
            "post": {
                "description": "查询客户端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "查询客户端",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Client"
                        }
                    }
                }
            }
        },
        "/client/{id}": {
            "get": {
                "description": "获取客户端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "获取客户端",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客户端ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Client"
                        }
                    }
                }
            },
            "post": {
                "description": "修改客户端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "修改客户端",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客户端ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "客户端信息",
                        "name": "client",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Client"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Client"
                        }
                    }
                }
            }
        },
        "/client/{id}/delete": {
            "get": {
                "description": "删除客户端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "删除客户端",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客户端ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Client"
                        }
                    }
                }
            }
        },
        "/client/{id}/disable": {
            "get": {
                "description": "禁用客户端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "禁用客户端",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客户端ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Client"
                        }
                    }
                }
            }
        },
        "/client/{id}/enable": {
            "get": {
                "description": "启用客户端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "启用客户端",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客户端ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Client"
                        }
                    }
                }
            }
        },
        "/client/{id}/start": {
            "get": {
                "description": "启动客户端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "启动客户端",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客户端ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Client"
                        }
                    }
                }
            }
        },
        "/client/{id}/stop": {
            "get": {
                "description": "停止客户端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "停止客户端",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客户端ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Client"
                        }
                    }
                }
            }
        },
        "/device/count": {
            "post": {
                "description": "查询设备数量",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "查询设备数量",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/device/create": {
            "post": {
                "description": "创建设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "创建设备",
                "parameters": [
                    {
                        "description": "设备信息",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Device"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Device"
                        }
                    }
                }
            }
        },
        "/device/export": {
            "get": {
                "description": "导出设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "product"
                ],
                "summary": "导出设备",
                "responses": {}
            }
        },
        "/device/import": {
            "post": {
                "description": "导入设备",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "导入设备",
                "parameters": [
                    {
                        "type": "file",
                        "description": "压缩包",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/device/list": {
            "get": {
                "description": "查询设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "查询设备",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Device"
                        }
                    }
                }
            }
        },
        "/device/search": {
            "post": {
                "description": "查询设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "查询设备",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Device"
                        }
                    }
                }
            }
        },
        "/device/{id}": {
            "get": {
                "description": "获取设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "获取设备",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "设备ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Device"
                        }
                    }
                }
            },
            "post": {
                "description": "修改设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "修改设备",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "设备ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "设备信息",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Device"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Device"
                        }
                    }
                }
            }
        },
        "/device/{id}/delete": {
            "get": {
                "description": "删除设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "删除设备",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "设备ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Device"
                        }
                    }
                }
            }
        },
        "/device/{id}/disable": {
            "get": {
                "description": "禁用设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "禁用设备",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "设备ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Device"
                        }
                    }
                }
            }
        },
        "/device/{id}/enable": {
            "get": {
                "description": "启用设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "启用设备",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "设备ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Device"
                        }
                    }
                }
            }
        },
        "/link/count": {
            "post": {
                "description": "查询连接数量",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link"
                ],
                "summary": "查询连接数量",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/link/export": {
            "get": {
                "description": "导出连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "product"
                ],
                "summary": "导出连接",
                "responses": {}
            }
        },
        "/link/import": {
            "post": {
                "description": "导入连接",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "导入连接",
                "parameters": [
                    {
                        "type": "file",
                        "description": "压缩包",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/link/list": {
            "get": {
                "description": "查询连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link"
                ],
                "summary": "查询连接",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Link"
                        }
                    }
                }
            }
        },
        "/link/search": {
            "post": {
                "description": "查询连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link"
                ],
                "summary": "查询连接",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Link"
                        }
                    }
                }
            }
        },
        "/link/{id}": {
            "get": {
                "description": "获取连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link"
                ],
                "summary": "获取连接",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "连接ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Link"
                        }
                    }
                }
            },
            "post": {
                "description": "修改连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link"
                ],
                "summary": "修改连接",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "连接ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "连接信息",
                        "name": "link",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Link"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Link"
                        }
                    }
                }
            }
        },
        "/link/{id}/delete": {
            "get": {
                "description": "删除连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link"
                ],
                "summary": "删除连接",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "连接ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Link"
                        }
                    }
                }
            }
        },
        "/link/{id}/disable": {
            "get": {
                "description": "禁用连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link"
                ],
                "summary": "禁用连接",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "连接ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Link"
                        }
                    }
                }
            }
        },
        "/link/{id}/enable": {
            "get": {
                "description": "启用连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link"
                ],
                "summary": "启用连接",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "连接ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Link"
                        }
                    }
                }
            }
        },
        "/link/{id}/stop": {
            "get": {
                "description": "停止连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "link"
                ],
                "summary": "停止连接",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "连接ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Link"
                        }
                    }
                }
            }
        },
        "/product/count": {
            "post": {
                "description": "查询产品数量",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "查询产品数量",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/product/create": {
            "post": {
                "description": "创建产品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "创建产品",
                "parameters": [
                    {
                        "description": "产品信息",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Product"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Product"
                        }
                    }
                }
            }
        },
        "/product/export": {
            "get": {
                "description": "导出产品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "product"
                ],
                "summary": "导出产品",
                "responses": {}
            }
        },
        "/product/import": {
            "post": {
                "description": "导入产品",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "导入产品",
                "parameters": [
                    {
                        "type": "file",
                        "description": "压缩包",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/product/list": {
            "get": {
                "description": "查询产品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "查询产品",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Product"
                        }
                    }
                }
            }
        },
        "/product/search": {
            "post": {
                "description": "查询产品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "查询产品",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Product"
                        }
                    }
                }
            }
        },
        "/product/{id}": {
            "get": {
                "description": "获取产品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "获取产品",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "产品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Product"
                        }
                    }
                }
            },
            "post": {
                "description": "修改产品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "修改产品",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "产品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "产品信息",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Product"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Product"
                        }
                    }
                }
            }
        },
        "/product/{id}/delete": {
            "get": {
                "description": "删除产品",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "删除产品",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "产品ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Product"
                        }
                    }
                }
            }
        },
        "/serial/count": {
            "post": {
                "description": "查询串口数量",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serial"
                ],
                "summary": "查询串口数量",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/serial/create": {
            "post": {
                "description": "创建串口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serial"
                ],
                "summary": "创建串口",
                "parameters": [
                    {
                        "description": "串口信息",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Serial"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Serial"
                        }
                    }
                }
            }
        },
        "/serial/export": {
            "get": {
                "description": "导出串口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "product"
                ],
                "summary": "导出串口",
                "responses": {}
            }
        },
        "/serial/import": {
            "post": {
                "description": "导入串口",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "导入串口",
                "parameters": [
                    {
                        "type": "file",
                        "description": "压缩包",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/serial/list": {
            "get": {
                "description": "查询串口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serial"
                ],
                "summary": "查询串口",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Serial"
                        }
                    }
                }
            }
        },
        "/serial/ports": {
            "get": {
                "description": "串口列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serial"
                ],
                "summary": "串口列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-string"
                        }
                    }
                }
            }
        },
        "/serial/search": {
            "post": {
                "description": "查询串口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serial"
                ],
                "summary": "查询串口",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Serial"
                        }
                    }
                }
            }
        },
        "/serial/{id}": {
            "get": {
                "description": "获取串口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serial"
                ],
                "summary": "获取串口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "串口ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Serial"
                        }
                    }
                }
            },
            "post": {
                "description": "修改串口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serial"
                ],
                "summary": "修改串口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "串口ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "串口信息",
                        "name": "serial",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Serial"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Serial"
                        }
                    }
                }
            }
        },
        "/serial/{id}/delete": {
            "get": {
                "description": "删除串口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serial"
                ],
                "summary": "删除串口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "串口ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Serial"
                        }
                    }
                }
            }
        },
        "/serial/{id}/disable": {
            "get": {
                "description": "禁用串口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serial"
                ],
                "summary": "禁用串口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "串口ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Serial"
                        }
                    }
                }
            }
        },
        "/serial/{id}/enable": {
            "get": {
                "description": "启用串口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serial"
                ],
                "summary": "启用串口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "串口ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Serial"
                        }
                    }
                }
            }
        },
        "/serial/{id}/start": {
            "get": {
                "description": "启动串口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serial"
                ],
                "summary": "启动串口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "串口ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Serial"
                        }
                    }
                }
            }
        },
        "/serial/{id}/stop": {
            "get": {
                "description": "停止串口",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "serial"
                ],
                "summary": "停止串口",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "串口ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Serial"
                        }
                    }
                }
            }
        },
        "/server/count": {
            "post": {
                "description": "查询服务器数量",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "查询服务器数量",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/server/create": {
            "post": {
                "description": "创建服务器",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "创建服务器",
                "parameters": [
                    {
                        "description": "服务器信息",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Server"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Server"
                        }
                    }
                }
            }
        },
        "/server/export": {
            "get": {
                "description": "导出服务端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "product"
                ],
                "summary": "导出服务端",
                "responses": {}
            }
        },
        "/server/import": {
            "post": {
                "description": "导入服务端",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "导入服务端",
                "parameters": [
                    {
                        "type": "file",
                        "description": "压缩包",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/server/list": {
            "get": {
                "description": "查询服务器",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "查询服务器",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Server"
                        }
                    }
                }
            }
        },
        "/server/search": {
            "post": {
                "description": "查询服务器",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "查询服务器",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Server"
                        }
                    }
                }
            }
        },
        "/server/{id}": {
            "get": {
                "description": "获取服务器",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "获取服务器",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "服务器ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Server"
                        }
                    }
                }
            },
            "post": {
                "description": "修改服务器",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "修改服务器",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "服务器ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "服务器信息",
                        "name": "server",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Server"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Server"
                        }
                    }
                }
            }
        },
        "/server/{id}/delete": {
            "get": {
                "description": "删除服务器",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "删除服务器",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "服务器ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Server"
                        }
                    }
                }
            }
        },
        "/server/{id}/disable": {
            "get": {
                "description": "禁用服务器",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "禁用服务器",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "服务器ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Server"
                        }
                    }
                }
            }
        },
        "/server/{id}/enable": {
            "get": {
                "description": "启用服务器",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "启用服务器",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "服务器ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Server"
                        }
                    }
                }
            }
        },
        "/server/{id}/start": {
            "get": {
                "description": "启动服务端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "启动服务端",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "服务端ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Server"
                        }
                    }
                }
            }
        },
        "/server/{id}/stop": {
            "get": {
                "description": "停止服务端",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "停止服务端",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "服务端ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Server"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ParamSearch": {
            "type": "object",
            "properties": {
                "filter": {
                    "type": "object",
                    "additionalProperties": true
                },
                "keyword": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "skip": {
                    "type": "integer"
                },
                "sort": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                }
            }
        },
        "api.ReplyData-int64": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "api.ReplyData-string": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "api.ReplyData-types_Client": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.Client"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "api.ReplyData-types_Device": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.Device"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "api.ReplyData-types_Link": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.Link"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "api.ReplyData-types_Product": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.Product"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "api.ReplyData-types_Serial": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.Serial"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "api.ReplyData-types_Server": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.Server"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "api.ReplyList-types_Client": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Client"
                    }
                },
                "error": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.ReplyList-types_Device": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Device"
                    }
                },
                "error": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.ReplyList-types_Link": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Link"
                    }
                },
                "error": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.ReplyList-types_Product": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Product"
                    }
                },
                "error": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.ReplyList-types_Serial": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Serial"
                    }
                },
                "error": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.ReplyList-types_Server": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Server"
                    }
                },
                "error": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "types.Calculator": {
            "type": "object",
            "properties": {
                "expression": {
                    "description": "表达式",
                    "type": "string"
                },
                "name": {
                    "description": "赋值",
                    "type": "string"
                }
            }
        },
        "types.Client": {
            "type": "object",
            "properties": {
                "addr": {
                    "description": "地址，主机名或IP",
                    "type": "string"
                },
                "created": {
                    "description": "创建时间",
                    "type": "string"
                },
                "desc": {
                    "description": "说明",
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "heartbeat": {
                    "description": "心跳包",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "net": {
                    "description": "类型 tcp udp",
                    "type": "string"
                },
                "poller_interval": {
                    "description": "采集间隔",
                    "type": "integer"
                },
                "poller_period": {
                    "description": "采集周期",
                    "type": "integer"
                },
                "port": {
                    "description": "端口号",
                    "type": "integer"
                },
                "protocol_name": {
                    "description": "协议 rtu tcp parallel-tcp",
                    "type": "string"
                },
                "protocol_options": {
                    "description": "协议参数",
                    "type": "object",
                    "additionalProperties": {}
                },
                "retry_maximum": {
                    "description": "最大次数",
                    "type": "integer"
                },
                "retry_timeout": {
                    "description": "重试时间",
                    "type": "integer"
                },
                "running": {
                    "type": "boolean"
                }
            }
        },
        "types.DefaultDevice": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "product_id": {
                    "description": "产品ID",
                    "type": "string"
                },
                "slave": {
                    "description": "从站号",
                    "type": "integer"
                }
            }
        },
        "types.Device": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "desc": {
                    "description": "说明",
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "online": {
                    "type": "boolean"
                },
                "product_id": {
                    "description": "产品ID",
                    "type": "string"
                },
                "station": {
                    "description": "从站配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.Station"
                        }
                    ]
                },
                "tunnel_id": {
                    "description": "通道",
                    "type": "string"
                }
            }
        },
        "types.Filter": {
            "type": "object",
            "properties": {
                "expression": {
                    "description": "表达式",
                    "type": "string"
                },
                "name": {
                    "description": "字段",
                    "type": "string"
                }
            }
        },
        "types.Link": {
            "type": "object",
            "properties": {
                "created": {
                    "description": "创建时间",
                    "type": "string"
                },
                "desc": {
                    "description": "说明",
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "heartbeat": {
                    "description": "心跳包",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "poller_interval": {
                    "description": "采集间隔",
                    "type": "integer"
                },
                "poller_period": {
                    "description": "采集周期",
                    "type": "integer"
                },
                "protocol_name": {
                    "description": "协议 rtu tcp parallel-tcp",
                    "type": "string"
                },
                "protocol_options": {
                    "description": "协议参数",
                    "type": "object",
                    "additionalProperties": {}
                },
                "remote": {
                    "description": "远程地址",
                    "type": "string"
                },
                "running": {
                    "type": "boolean"
                },
                "server_id": {
                    "description": "服务器ID",
                    "type": "string"
                }
            }
        },
        "types.Mapper": {
            "type": "object",
            "properties": {
                "addr": {
                    "type": "integer"
                },
                "area": {
                    "type": "integer"
                },
                "code": {
                    "type": "integer"
                },
                "points": {
                    "description": "数据点",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Point"
                    }
                },
                "size": {
                    "description": "长度",
                    "type": "integer"
                }
            }
        },
        "types.Point": {
            "type": "object",
            "properties": {
                "be": {
                    "description": "大端模式",
                    "type": "boolean"
                },
                "bits": {
                    "description": "位，1 2 3...",
                    "type": "integer"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "offset": {
                    "description": "偏移",
                    "type": "integer"
                },
                "rate": {
                    "description": "倍率",
                    "type": "number"
                },
                "type": {
                    "description": "类型",
                    "type": "string"
                }
            }
        },
        "types.Product": {
            "type": "object",
            "properties": {
                "calculators": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Calculator"
                    }
                },
                "created": {
                    "description": "创建时间",
                    "type": "string"
                },
                "desc": {
                    "description": "说明",
                    "type": "string"
                },
                "filters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Filter"
                    }
                },
                "id": {
                    "type": "string"
                },
                "mappers": {
                    "description": "model.Product ` + "`" + `xorm:\"extends\"` + "`" + `",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Mapper"
                    }
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                }
            }
        },
        "types.Serial": {
            "type": "object",
            "properties": {
                "baud_rate": {
                    "description": "9600 115200",
                    "type": "integer"
                },
                "created": {
                    "description": "创建时间",
                    "type": "string"
                },
                "data_bits": {
                    "description": "5 6 7 8",
                    "type": "integer"
                },
                "desc": {
                    "description": "说明",
                    "type": "string"
                },
                "disabled": {
                    "type": "boolean"
                },
                "heartbeat": {
                    "description": "心跳包",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "parity_mode": {
                    "description": "0 1 2 NONE ODD EVEN",
                    "type": "integer"
                },
                "poller_interval": {
                    "description": "采集间隔",
                    "type": "integer"
                },
                "poller_period": {
                    "description": "采集周期",
                    "type": "integer"
                },
                "port_name": {
                    "description": "port, e.g. COM1 \"/dev/ttySerial1\".",
                    "type": "string"
                },
                "protocol_name": {
                    "description": "协议 rtu tcp parallel-tcp",
                    "type": "string"
                },
                "protocol_options": {
                    "description": "协议参数",
                    "type": "object",
                    "additionalProperties": {}
                },
                "retry_maximum": {
                    "description": "最大次数",
                    "type": "integer"
                },
                "retry_timeout": {
                    "description": "重试时间",
                    "type": "integer"
                },
                "running": {
                    "type": "boolean"
                },
                "stop_bits": {
                    "description": "1 2",
                    "type": "integer"
                }
            }
        },
        "types.Server": {
            "type": "object",
            "properties": {
                "created": {
                    "description": "创建时间",
                    "type": "string"
                },
                "desc": {
                    "description": "说明",
                    "type": "string"
                },
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.DefaultDevice"
                    }
                },
                "disabled": {
                    "type": "boolean"
                },
                "heartbeat": {
                    "description": "心跳包",
                    "type": "string"
                },
                "id": {
                    "description": "ID",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "poller_interval": {
                    "description": "采集间隔",
                    "type": "integer"
                },
                "poller_period": {
                    "description": "采集周期",
                    "type": "integer"
                },
                "port": {
                    "description": "监听端口",
                    "type": "integer"
                },
                "protocol_name": {
                    "description": "协议 rtu tcp parallel-tcp",
                    "type": "string"
                },
                "protocol_options": {
                    "description": "协议参数",
                    "type": "object",
                    "additionalProperties": {}
                },
                "running": {
                    "type": "boolean"
                },
                "standalone": {
                    "description": "单例模式（不支持注册）",
                    "type": "boolean"
                }
            }
        },
        "types.Station": {
            "type": "object",
            "additionalProperties": {
                "type": "integer"
            }
        }
    }
}`

// SwaggerInfogateway holds exported Swagger Info so clients can modify it
var SwaggerInfogateway = &swag.Spec{
	Version:          "1.0 版本",
	Host:             "",
	BasePath:         "/api/gateway/api/",
	Schemes:          []string{},
	Title:            "物联大师网关接口文档",
	Description:      "API文档",
	InfoInstanceName: "gateway",
	SwaggerTemplate:  docTemplategateway,
}

func init() {
	swag.Register(SwaggerInfogateway.InstanceName(), SwaggerInfogateway)
}
